### PR TITLE
Added npm install to readme

### PR DESCRIPTION
**Pull request by PavelGonzales**
Cheers! :beer:

### CODE REVIEW

**Comment by PavelGonzales** [comment]
Please do `npm publish` from repo folder.

npmjs.com has `0.1.2` version (when actual is `0.2.7`)

**Comment by matthewhudson** [comment]
I'll need to work with @soenkekluth to make this happen. 

@soenkekluth - ping?

**Comment by linsmalldragon** [comment]
There 's no 0.2.7 version in npm. @matthewhudson Has that been published to npm?

**Comment by matthewhudson** [comment]
@PavelGonzales @linsmalldragon The `device.js` package in NPM isn't this one, it's owned by @soenkekluth: https://www.npmjs.com/package/device.js

**Comment by matthewhudson** [comment]
Closing b/c this is a dupe of https://github.com/matthewhudson/device.js/issues/85, and doesn't solve the current issue. We'll need to decide on a new name unless @soenkekluth can respond.

**Pull request closed without merging**
