### PR TITLE
Publish to NPM / Rename Project

### PR DESCRIPTION
**Pull request by matthewhudson**
Addresses #85

Unfortunately, the `device.js` name (and all variations) is already parked in NPM. I've reached out to a few folks over the *years* but haven't been able to secure the original project name.

Publishing this to NPM is long overdue. The most sensible solution seems to be to simply change the project name to something that's available in the NPM registry.

This PR is a WIP step towards renaming and publishing. At the moment, I think the new name will be `uasniffer`. Maybe not the best name, but gets us over this hurdle. 

Open to suggestions though...

### CODE REVIEW

**Comment by JSteunou** [comment]
Include *ua* in the name might mislead people because this lib does not tell if it is firefox or chrome... It gives intel about the device.

You should keep *device* in the name or a ref to it and avoid ref to ua

**Comment by matthewhudson** [comment]
Good point. Other potential options:
- `device-intel`
- `device-check`

**Comment by JSteunou** [comment]
*device-intel* is the simplest and match what this lib does. Which I had creative imagination to come up with a fun but descriptive name. [Naming things is hard](http://hilton.org.uk/blog/why-naming-things-is-hard)

**Comment by rcotter** [comment]
current-device

**Comment by matthewhudson** [comment]
@rcotter @JSteunou Beautiful - thank you both. I'm going to let this sit ~36hrs for others to chime in w/ thoughts.

**Comment by sabsaxo** [comment]
https://www.npmjs.com/search?q=dvice

**Pull request closed without merging**
