### PR TITLE
Publish to NPM

### PR DESCRIPTION
**Pull request by matthewhudson**
Now published to NPM as `current-device`.  Closes #109

### CODE REVIEW

**Comment by nebrot** [comment]
Could you make a new github-release please. Is there no more device.js and device.min.js?

**Comment by matthewhudson** [comment]
device.js and device.min.js have been replaced with `./src/index.js`.

**Comment by matthewhudson** [comment]
@nebrot Let me know if there's a specific use-case I can help with.

**Comment by nebrot** [comment]
First, thank you for this great script!

> device.js and device.min.js have been replaced with ./src/index.js.

What's the reason for this change? In many smaller static sites we don't have a build process (minification, concatening etc.). So `current-device.js` and `current-device.min.js` would be nice in the release-dist like in the past and in other popular scripts/libs like
- [jquery](https://code.jquery.com/jquery-3.2.1.min.js)
- [jquery-ui](https://code.jquery.com/ui/1.12.1/jquery-ui.min.js)
- [bootstrap](https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js)
- [moment.js](https://momentjs.com/downloads/moment.min.js)
- [fancybox](https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js)

and many other.

**Comment by matthewhudson** [comment]
I can look into refining the build process to potentially provide a minified build for such a use-case.

In the meantime, you might benefit from using `unpkg`:

``` html
<script src="https://unpkg.com/current-device"></script>
```

**Pull request merged**
